apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yoga-app
  namespace: yoga-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - yourdomain.com
      secretName: yoga-app-tls
  rules:
    - host: yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: yoga-app
                port:
                  number: 80
