apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: nirlipta-yoga
type: Opaque
stringData:
  # JWT Secret - change in production!
  JWT_SECRET: nirlipta-yoga-super-secret-jwt-key-2024-change-this
  
  # Google OAuth - update with your credentials
  GOOGLE_CLIENT_ID: your-google-client-id
  GOOGLE_CLIENT_SECRET: your-google-client-secret
  
  # Facebook OAuth - update with your credentials
  FACEBOOK_CLIENT_ID: your-facebook-client-id
  FACEBOOK_CLIENT_SECRET: your-facebook-client-secret

